name: my first github workflow
on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
            - name: Running multiple command in single steps
              run: |
                echo "Run Multople command"
                ls
                cat README.md