name: generate ascii artwork
on: workflow_dispatch
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: copy cowsay program 
              run: sudo apt-get install cowsay -y
            - name: Execute cowsay command
              run: cowsay -f dragon "Run for cover, I am a Dragon .............RWAR" >> dragon.txt
            - uses: actions/upload-artifact@v7
              with:
                 name: upload-dragon-file
                 path: dragon.txt
            - name: sleep for 30 sec
              run: sleep 30
    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifact@v8
            with:
                name: upload-dragon-file
          - name: Test file exist
            run: grep -i "dragon" dragon.txt

    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v8
              with:
                name: upload-dragon-file
            - name: Read File
              run: cat dragon.txt
            - name: Executing shell script
              run: echo Deploying .................

