name: Exploring Variables and secrets

on: push

env:
    REGISTRY: docker.io
    USERNAME: ninad262002
    IMAGE_NAME: nginx-project

jobs:
    build:
        runs-on: ubuntu:latest

        steps:
          - name: check docker version 
            run: docker --version 
          - name: Build Image
            run: docker build -t $REGISTRY/$USERNAME/$IMAGE_NAME:latest .
          - name: Push Image
            run: docker push $REGISTRY/$USERNAME/$IMAGE_NAME:latest

