name: use existing docker image

on: push

jobs:
    run_container:
        runs-on: ubuntu-latest
        env:
            REGISTRY: ninadmahure
            IMAGE: flask-devops-app:latest
        steps:
            - name: Pull Image
              run: docker pull $REGISTRY/${{env.IMAGE }}
            - name: Run container
              run: |
                docker run -d -p 5000:5000 --name flask-app $REGISTRY/${{env.IMAGE }}
            - run: sleep 6000s
            - name: check running containers
              run: docker ps


