name: use existing docker image

on: push

jobs:
    run_container:
        runs-on: ubuntu-latest
        steps:
            - name: Pull Image
              run: docker pull ninadmahure/flask-devops-app:latest
            - name: Run container
              run: |
                docker run -d -p 5000:5000 --name flask-app ninadmahure/flask-devops-app:latest
            - name: check running containers
              run: docker ps


